using NetLift.Core.Interfaces;
using NetLift.Core.Models;
using System.Text;

namespace NetLift.Git;

/// <summary>
/// Generates automatic commits for migration transformations with conventional commit messages.
/// </summary>
public class CommitGenerator : ICommitGenerator
{
    private readonly IGitOperations _gitOperations;
    private const string DefaultAuthorName = "NetLift";
    private const string DefaultAuthorEmail = "netlift@migration.local";
    private const int MaxFilesInMessage = 20;

    /// <summary>
    /// Initializes a new instance of the <see cref="CommitGenerator"/> class.
    /// </summary>
    /// <param name="gitOperations">The Git operations service.</param>
    public CommitGenerator(IGitOperations gitOperations)
    {
        _gitOperations = gitOperations ?? throw new ArgumentNullException(nameof(gitOperations));
    }

    /// <inheritdoc />
    public Task<string> GenerateCommitMessageAsync(
        MigrationPhaseType phase,
        IEnumerable<string> changedFiles)
    {
        var filesList = changedFiles.ToList();
        var sb = new StringBuilder();

        // Subject line (conventional commit format)
        var prefix = GetConventionalPrefix(phase);
        var phaseDescription = GetPhaseDescription(phase);
        sb.AppendLine($"{prefix}(migration): {phaseDescription}");
        sb.AppendLine();

        // Body - file list
        if (filesList.Any())
        {
            sb.AppendLine("Modified files:");
            var filesToShow = filesList.Take(MaxFilesInMessage);
            foreach (var file in filesToShow)
            {
                sb.AppendLine($"  - {file}");
            }

            if (filesList.Count > MaxFilesInMessage)
            {
                sb.AppendLine($"  ... and {filesList.Count - MaxFilesInMessage} more");
            }
            sb.AppendLine();
        }

        // Footer
        sb.AppendLine("Generated by NetLift");

        return Task.FromResult(sb.ToString());
    }

    /// <inheritdoc />
    public async Task<string> CommitChangesAsync(
        string repoPath,
        MigrationPhaseType phase,
        IEnumerable<string> changedFiles)
    {
        if (string.IsNullOrWhiteSpace(repoPath))
        {
            throw new ArgumentException("Repository path cannot be null or whitespace.", nameof(repoPath));
        }

        var filesList = changedFiles.ToList();
        if (!filesList.Any())
        {
            return string.Empty;
        }

        // Stage all changed files
        await _gitOperations.StageAsync(repoPath, filesList);

        // Check if there are actually staged changes
        var hasChanges = await _gitOperations.HasUncommittedChangesAsync(repoPath);
        if (!hasChanges)
        {
            return string.Empty;
        }

        // Generate commit message
        var message = await GenerateCommitMessageAsync(phase, filesList);

        // Create commit
        var commitSha = await _gitOperations.CommitAsync(
            repoPath,
            message,
            DefaultAuthorName,
            DefaultAuthorEmail);

        return commitSha;
    }

    /// <summary>
    /// Gets the conventional commit prefix for the specified migration phase.
    /// </summary>
    /// <param name="phase">The migration phase type.</param>
    /// <returns>The conventional commit prefix (feat, refactor, chore, etc.).</returns>
    private static string GetConventionalPrefix(MigrationPhaseType phase) => phase switch
    {
        MigrationPhaseType.ProjectFiles => "refactor",
        MigrationPhaseType.Configuration => "refactor",
        MigrationPhaseType.Controllers => "feat",
        MigrationPhaseType.EntityFramework => "feat",
        MigrationPhaseType.Wcf => "feat",
        MigrationPhaseType.Validation => "feat",
        _ => "chore"
    };

    /// <summary>
    /// Gets a human-readable description of the migration phase.
    /// </summary>
    /// <param name="phase">The migration phase type.</param>
    /// <returns>A description of the migration phase.</returns>
    private static string GetPhaseDescription(MigrationPhaseType phase) => phase switch
    {
        MigrationPhaseType.ProjectFiles => "migrate project files to SDK-style format",
        MigrationPhaseType.Configuration => "migrate configuration to appsettings.json",
        MigrationPhaseType.Controllers => "migrate ASP.NET MVC controllers to ASP.NET Core",
        MigrationPhaseType.EntityFramework => "migrate Entity Framework to EF Core",
        MigrationPhaseType.Wcf => "migrate WCF services to gRPC/REST",
        MigrationPhaseType.Validation => "migrate validation to ASP.NET Core",
        _ => "apply migration changes"
    };
}
