using NetLift.Core.Interfaces.SignalR;
using NetLift.Core.Models.SignalR;

namespace NetLift.Transforms.SignalR.Generators;

/// <summary>
/// Generates ASP.NET Core SignalR startup configuration code.
/// </summary>
public class SignalRStartupGenerator : ISignalRStartupGenerator
{
    /// <inheritdoc />
    public string GenerateServiceRegistration()
    {
        return "builder.Services.AddSignalR();";
    }

    /// <inheritdoc />
    public string GenerateEndpointMappings(IReadOnlyList<SignalRHubInfo> hubs)
    {
        if (!hubs.Any())
        {
            return "// No SignalR hubs detected";
        }

        var lines = new List<string>();

        foreach (var hub in hubs)
        {
            var route = hub.HubRoute ?? $"/{hub.ClassName.ToLowerInvariant()}";
            lines.Add($"app.MapHub<{hub.ClassName}>(\"{route}\");");
        }

        return string.Join("\n", lines);
    }

    /// <inheritdoc />
    public string GenerateFullConfiguration(IReadOnlyList<SignalRHubInfo> hubs)
    {
        var serviceRegistration = GenerateServiceRegistration();
        var endpointMappings = GenerateEndpointMappings(hubs);

        var code = $@"// ==============================
// SignalR Configuration (Generated by NetLift)
// ==============================

// Add to Program.cs after var builder = WebApplication.CreateBuilder(args);
{serviceRegistration}

// Add to Program.cs after app.UseRouting(); and app.UseAuthorization();
{endpointMappings}

// ==============================
// Client-side changes required:
// ==============================
// 1. Update npm package: npm install @microsoft/signalr
// 2. Update JavaScript client code:
//
// Old (jquery.signalR):
//   var connection = $.hubConnection();
//   var hub = connection.createHubProxy('myHub');
//   hub.on('messageReceived', function(msg) {{ ... }});
//   connection.start();
//
// New (@microsoft/signalr):
//   import * as signalR from '@microsoft/signalr';
//   const connection = new signalR.HubConnectionBuilder()
//       .withUrl('/myHub')
//       .build();
//   connection.on('messageReceived', (msg) => {{ ... }});
//   connection.start();
// ==============================
";

        return code;
    }
}
