using FluentAssertions;
using Moq;
using NetLift.Core.Interfaces;
using NetLift.Core.Models;
using NetLift.Git;

namespace NetLift.Tests.Unit.Git;

public class CommitGeneratorTests
{
    private readonly Mock<IGitOperations> _gitOperationsMock;
    private readonly CommitGenerator _commitGenerator;

    public CommitGeneratorTests()
    {
        _gitOperationsMock = new Mock<IGitOperations>();
        _commitGenerator = new CommitGenerator(_gitOperationsMock.Object);
    }

    [Fact]
    public void Constructor_WithNullGitOperations_ThrowsArgumentNullException()
    {
        // Act
        var act = () => new CommitGenerator(null!);

        // Assert
        act.Should().Throw<ArgumentNullException>()
            .WithParameterName("gitOperations");
    }

    [Theory]
    [InlineData(MigrationPhaseType.ProjectFiles, "refactor(migration): migrate project files to SDK-style format")]
    [InlineData(MigrationPhaseType.Configuration, "refactor(migration): migrate configuration to appsettings.json")]
    [InlineData(MigrationPhaseType.Controllers, "feat(migration): migrate ASP.NET MVC controllers to ASP.NET Core")]
    [InlineData(MigrationPhaseType.EntityFramework, "feat(migration): migrate Entity Framework to EF Core")]
    [InlineData(MigrationPhaseType.Wcf, "feat(migration): migrate WCF services to gRPC/REST")]
    [InlineData(MigrationPhaseType.Validation, "feat(migration): migrate validation to ASP.NET Core")]
    public async Task GenerateCommitMessageAsync_WithPhase_GeneratesCorrectSubjectLine(
        MigrationPhaseType phase,
        string expectedSubjectLine)
    {
        // Arrange
        var changedFiles = new[] { "test.cs" };

        // Act
        var message = await _commitGenerator.GenerateCommitMessageAsync(phase, changedFiles);

        // Assert
        message.Should().StartWith(expectedSubjectLine);
    }

    [Fact]
    public async Task GenerateCommitMessageAsync_WithSingleFile_IncludesFileInMessage()
    {
        // Arrange
        var changedFiles = new[] { "src/Project/Test.cs" };

        // Act
        var message = await _commitGenerator.GenerateCommitMessageAsync(
            MigrationPhaseType.ProjectFiles,
            changedFiles);

        // Assert
        message.Should().Contain("Modified files:");
        message.Should().Contain("  - src/Project/Test.cs");
    }

    [Fact]
    public async Task GenerateCommitMessageAsync_WithMultipleFiles_IncludesAllFiles()
    {
        // Arrange
        var changedFiles = new[]
        {
            "src/Project1/Test1.cs",
            "src/Project2/Test2.cs",
            "src/Project3/Test3.cs"
        };

        // Act
        var message = await _commitGenerator.GenerateCommitMessageAsync(
            MigrationPhaseType.Controllers,
            changedFiles);

        // Assert
        message.Should().Contain("Modified files:");
        message.Should().Contain("  - src/Project1/Test1.cs");
        message.Should().Contain("  - src/Project2/Test2.cs");
        message.Should().Contain("  - src/Project3/Test3.cs");
    }

    [Fact]
    public async Task GenerateCommitMessageAsync_WithMoreThan20Files_TruncatesFileList()
    {
        // Arrange
        var changedFiles = Enumerable.Range(1, 25)
            .Select(i => $"src/Project{i}/Test{i}.cs")
            .ToArray();

        // Act
        var message = await _commitGenerator.GenerateCommitMessageAsync(
            MigrationPhaseType.ProjectFiles,
            changedFiles);

        // Assert
        message.Should().Contain("Modified files:");
        message.Should().Contain("  - src/Project1/Test1.cs");
        message.Should().Contain("  - src/Project20/Test20.cs");
        message.Should().Contain("  ... and 5 more");
        message.Should().NotContain("src/Project21/Test21.cs");
    }

    [Fact]
    public async Task GenerateCommitMessageAsync_Always_IncludesNetLiftFooter()
    {
        // Arrange
        var changedFiles = new[] { "test.cs" };

        // Act
        var message = await _commitGenerator.GenerateCommitMessageAsync(
            MigrationPhaseType.ProjectFiles,
            changedFiles);

        // Assert
        message.Should().Contain("Generated by NetLift");
    }

    [Fact]
    public async Task GenerateCommitMessageAsync_WithNoFiles_GeneratesMessageWithoutFileList()
    {
        // Arrange
        var changedFiles = Array.Empty<string>();

        // Act
        var message = await _commitGenerator.GenerateCommitMessageAsync(
            MigrationPhaseType.ProjectFiles,
            changedFiles);

        // Assert
        message.Should().NotContain("Modified files:");
        message.Should().Contain("Generated by NetLift");
    }

    [Fact]
    public async Task CommitChangesAsync_WithNullRepoPath_ThrowsArgumentException()
    {
        // Arrange
        var changedFiles = new[] { "test.cs" };

        // Act
        var act = async () => await _commitGenerator.CommitChangesAsync(
            null!,
            MigrationPhaseType.ProjectFiles,
            changedFiles);

        // Assert
        await act.Should().ThrowAsync<ArgumentException>()
            .WithParameterName("repoPath");
    }

    [Fact]
    public async Task CommitChangesAsync_WithEmptyRepoPath_ThrowsArgumentException()
    {
        // Arrange
        var changedFiles = new[] { "test.cs" };

        // Act
        var act = async () => await _commitGenerator.CommitChangesAsync(
            "",
            MigrationPhaseType.ProjectFiles,
            changedFiles);

        // Assert
        await act.Should().ThrowAsync<ArgumentException>()
            .WithParameterName("repoPath");
    }

    [Fact]
    public async Task CommitChangesAsync_WithNoChangedFiles_ReturnsEmptyString()
    {
        // Arrange
        var changedFiles = Array.Empty<string>();

        // Act
        var result = await _commitGenerator.CommitChangesAsync(
            "F:\\repo",
            MigrationPhaseType.ProjectFiles,
            changedFiles);

        // Assert
        result.Should().BeEmpty();
        _gitOperationsMock.Verify(
            x => x.StageAsync(It.IsAny<string>(), It.IsAny<IEnumerable<string>>()),
            Times.Never);
    }

    [Fact]
    public async Task CommitChangesAsync_WithNoStagedChanges_ReturnsEmptyString()
    {
        // Arrange
        var repoPath = "F:\\repo";
        var changedFiles = new[] { "test.cs" };

        _gitOperationsMock
            .Setup(x => x.HasUncommittedChangesAsync(repoPath))
            .ReturnsAsync(false);

        // Act
        var result = await _commitGenerator.CommitChangesAsync(
            repoPath,
            MigrationPhaseType.ProjectFiles,
            changedFiles);

        // Assert
        result.Should().BeEmpty();
        _gitOperationsMock.Verify(
            x => x.StageAsync(repoPath, changedFiles),
            Times.Once);
        _gitOperationsMock.Verify(
            x => x.CommitAsync(
                It.IsAny<string>(),
                It.IsAny<string>(),
                It.IsAny<string>(),
                It.IsAny<string>()),
            Times.Never);
    }

    [Fact]
    public async Task CommitChangesAsync_WithValidChanges_StagesFiles()
    {
        // Arrange
        var repoPath = "F:\\repo";
        var changedFiles = new[] { "src/Test1.cs", "src/Test2.cs" };

        _gitOperationsMock
            .Setup(x => x.HasUncommittedChangesAsync(repoPath))
            .ReturnsAsync(true);
        _gitOperationsMock
            .Setup(x => x.CommitAsync(
                It.IsAny<string>(),
                It.IsAny<string>(),
                It.IsAny<string>(),
                It.IsAny<string>()))
            .ReturnsAsync("abc123");

        // Act
        await _commitGenerator.CommitChangesAsync(
            repoPath,
            MigrationPhaseType.Controllers,
            changedFiles);

        // Assert
        _gitOperationsMock.Verify(
            x => x.StageAsync(repoPath, changedFiles),
            Times.Once);
    }

    [Fact]
    public async Task CommitChangesAsync_WithValidChanges_CreatesCommitWithGeneratedMessage()
    {
        // Arrange
        var repoPath = "F:\\repo";
        var changedFiles = new[] { "src/Test.cs" };
        var expectedCommitSha = "abc123def456";

        _gitOperationsMock
            .Setup(x => x.HasUncommittedChangesAsync(repoPath))
            .ReturnsAsync(true);
        _gitOperationsMock
            .Setup(x => x.CommitAsync(
                repoPath,
                It.Is<string>(msg => msg.Contains("refactor(migration): migrate project files to SDK-style format")),
                "NetLift",
                "netlift@migration.local"))
            .ReturnsAsync(expectedCommitSha);

        // Act
        var result = await _commitGenerator.CommitChangesAsync(
            repoPath,
            MigrationPhaseType.ProjectFiles,
            changedFiles);

        // Assert
        result.Should().Be(expectedCommitSha);
        _gitOperationsMock.Verify(
            x => x.CommitAsync(
                repoPath,
                It.Is<string>(msg =>
                    msg.Contains("refactor(migration): migrate project files to SDK-style format") &&
                    msg.Contains("src/Test.cs") &&
                    msg.Contains("Generated by NetLift")),
                "NetLift",
                "netlift@migration.local"),
            Times.Once);
    }

    [Fact]
    public async Task CommitChangesAsync_WithValidChanges_UsesDefaultAuthorInformation()
    {
        // Arrange
        var repoPath = "F:\\repo";
        var changedFiles = new[] { "test.cs" };

        _gitOperationsMock
            .Setup(x => x.HasUncommittedChangesAsync(repoPath))
            .ReturnsAsync(true);
        _gitOperationsMock
            .Setup(x => x.CommitAsync(
                It.IsAny<string>(),
                It.IsAny<string>(),
                It.IsAny<string>(),
                It.IsAny<string>()))
            .ReturnsAsync("abc123");

        // Act
        await _commitGenerator.CommitChangesAsync(
            repoPath,
            MigrationPhaseType.ProjectFiles,
            changedFiles);

        // Assert
        _gitOperationsMock.Verify(
            x => x.CommitAsync(
                repoPath,
                It.IsAny<string>(),
                "NetLift",
                "netlift@migration.local"),
            Times.Once);
    }

    [Fact]
    public async Task CommitChangesAsync_WithConfigurationPhase_GeneratesCorrectCommitMessage()
    {
        // Arrange
        var repoPath = "F:\\repo";
        var changedFiles = new[] { "appsettings.json", "Web.config" };

        _gitOperationsMock
            .Setup(x => x.HasUncommittedChangesAsync(repoPath))
            .ReturnsAsync(true);
        _gitOperationsMock
            .Setup(x => x.CommitAsync(
                It.IsAny<string>(),
                It.IsAny<string>(),
                It.IsAny<string>(),
                It.IsAny<string>()))
            .ReturnsAsync("abc123");

        // Act
        await _commitGenerator.CommitChangesAsync(
            repoPath,
            MigrationPhaseType.Configuration,
            changedFiles);

        // Assert
        _gitOperationsMock.Verify(
            x => x.CommitAsync(
                repoPath,
                It.Is<string>(msg => msg.Contains("refactor(migration): migrate configuration to appsettings.json")),
                It.IsAny<string>(),
                It.IsAny<string>()),
            Times.Once);
    }
}
