using System.Text;
using NetLift.Core.Interfaces;
using NetLift.Core.Models.Wcf;

namespace NetLift.Transforms.Wcf.Generators;

/// <summary>
/// Generates client proxy code for consuming gRPC and REST APIs migrated from WCF.
/// </summary>
public sealed class ClientProxyGenerator : IClientProxyGenerator
{
    private readonly List<string> _diagnostics = [];
    private int _confidenceScore = 100;

    /// <inheritdoc />
    public int ConfidenceScore => _confidenceScore;

    /// <inheritdoc />
    public IReadOnlyCollection<string> Diagnostics => _diagnostics.AsReadOnly();

    /// <inheritdoc />
    public ClientProxyInfo Generate(WcfServiceContract serviceContract, string targetNamespace)
    {
        if (serviceContract == null)
            throw new ArgumentNullException(nameof(serviceContract));
        if (string.IsNullOrWhiteSpace(targetNamespace))
            throw new ArgumentException("Target namespace cannot be null or whitespace.", nameof(targetNamespace));

        // Reset state
        _diagnostics.Clear();
        _confidenceScore = 100;

        // Derive service and client names
        var serviceName = serviceContract.Name ??
            (serviceContract.InterfaceName.StartsWith('I') && serviceContract.InterfaceName.Length > 1
                ? serviceContract.InterfaceName.Substring(1)
                : serviceContract.InterfaceName);
        var interfaceName = $"I{serviceName}Client";

        // Check for unsupported features
        if (serviceContract.SessionRequired)
        {
            _diagnostics.Add($"Service contract requires sessions. Client must manage correlation manually.");
            _confidenceScore = Math.Min(_confidenceScore, 75);
        }

        if (!string.IsNullOrWhiteSpace(serviceContract.CallbackContract))
        {
            _diagnostics.Add($"Service contract uses duplex pattern with callback '{serviceContract.CallbackContract}'. Consider using gRPC bidirectional streaming or SignalR.");
            _confidenceScore = Math.Min(_confidenceScore, 65);
        }

        // Check for one-way operations
        if (serviceContract.Operations.Any(op => op.IsOneWay))
        {
            _diagnostics.Add("Service contains one-way operations. Client implementations will wait for acknowledgment.");
            _confidenceScore = Math.Min(_confidenceScore, 85);
        }

        // Generate client code
        var interfaceCode = GenerateClientInterface(interfaceName, targetNamespace, serviceContract.Operations);
        var grpcClientCode = GenerateGrpcClient(interfaceName, serviceName, targetNamespace, serviceContract.Operations);
        var httpClientCode = GenerateHttpClient(interfaceName, serviceName, targetNamespace, serviceContract.Operations);
        var extensionsCode = GenerateExtensions(interfaceName, serviceName, targetNamespace);

        return new ClientProxyInfo
        {
            InterfaceName = interfaceName,
            InterfaceCode = interfaceCode,
            GrpcClientCode = grpcClientCode,
            HttpClientCode = httpClientCode,
            ExtensionsCode = extensionsCode,
            Namespace = targetNamespace
        };
    }

    private string GenerateClientInterface(
        string interfaceName,
        string namespaceName,
        IReadOnlyList<WcfOperation> operations)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("namespace " + namespaceName + ";");
        sb.AppendLine();

        // Interface documentation
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Client interface for consuming the service.");
        sb.AppendLine("/// Generated by NetLift from WCF service contract.");
        sb.AppendLine("/// </summary>");

        // Interface declaration
        sb.AppendLine($"public interface {interfaceName}");
        sb.AppendLine("{");

        // Generate methods
        foreach (var operation in operations)
        {
            GenerateInterfaceMethod(sb, operation);
        }

        // Close interface
        sb.AppendLine("}");

        return sb.ToString();
    }

    private void GenerateInterfaceMethod(StringBuilder sb, WcfOperation operation)
    {
        // Method documentation
        sb.AppendLine("    /// <summary>");
        if (!string.IsNullOrWhiteSpace(operation.XmlDocumentation))
        {
            foreach (var line in operation.XmlDocumentation.Split('\n'))
            {
                sb.AppendLine($"    /// {line.Trim()}");
            }
        }
        else
        {
            sb.AppendLine($"    /// Calls the {operation.Name} operation.");
        }
        sb.AppendLine("    /// </summary>");

        // Parameters documentation
        foreach (var param in operation.Parameters)
        {
            sb.AppendLine($"    /// <param name=\"{param.Name}\">The {param.Name} parameter.</param>");
        }
        sb.AppendLine("    /// <param name=\"cancellationToken\">The cancellation token.</param>");
        sb.AppendLine("    /// <returns>The operation result.</returns>");

        // Method signature
        var returnType = MapReturnType(operation.ReturnType);
        var parameters = string.Join(", ", operation.Parameters.Select(p => $"{p.Type} {p.Name}"));
        if (!string.IsNullOrEmpty(parameters))
            parameters += ", ";

        sb.AppendLine($"    Task<{returnType}> {operation.Name}Async({parameters}CancellationToken cancellationToken = default);");
        sb.AppendLine();
    }

    private string GenerateGrpcClient(
        string interfaceName,
        string serviceName,
        string namespaceName,
        IReadOnlyList<WcfOperation> operations)
    {
        var sb = new StringBuilder();
        var className = $"{serviceName}GrpcClient";

        // File header
        sb.AppendLine("using Grpc.Core;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine();

        // Namespace
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();

        // Class documentation
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// gRPC client implementation for {serviceName}.");
        sb.AppendLine("/// Generated by NetLift from WCF service contract.");
        sb.AppendLine("/// </summary>");

        // Class declaration
        sb.AppendLine($"public sealed class {className} : {interfaceName}");
        sb.AppendLine("{");

        // Fields
        sb.AppendLine($"    private readonly {serviceName}.{serviceName}Client _grpcClient;");
        sb.AppendLine($"    private readonly ILogger<{className}> _logger;");
        sb.AppendLine();

        // Constructor
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Initializes a new instance of the <see cref=\"{className}\"/> class.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    /// <param name=\"grpcClient\">The proto-generated gRPC client.</param>");
        sb.AppendLine($"    /// <param name=\"logger\">The logger instance.</param>");
        sb.AppendLine($"    public {className}({serviceName}.{serviceName}Client grpcClient, ILogger<{className}> logger)");
        sb.AppendLine("    {");
        sb.AppendLine("        _grpcClient = grpcClient ?? throw new ArgumentNullException(nameof(grpcClient));");
        sb.AppendLine("        _logger = logger ?? throw new ArgumentNullException(nameof(logger));");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Generate methods
        foreach (var operation in operations)
        {
            GenerateGrpcMethod(sb, operation);
        }

        // Close class
        sb.AppendLine("}");

        return sb.ToString();
    }

    private void GenerateGrpcMethod(StringBuilder sb, WcfOperation operation)
    {
        var returnType = MapReturnType(operation.ReturnType);
        var parameters = string.Join(", ", operation.Parameters.Select(p => $"{p.Type} {p.Name}"));
        if (!string.IsNullOrEmpty(parameters))
            parameters += ", ";

        // Method documentation
        sb.AppendLine("    /// <inheritdoc />");

        // Method signature
        sb.AppendLine($"    public async Task<{returnType}> {operation.Name}Async({parameters}CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");

        // Method body
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine($"            _logger.LogDebug(\"Calling {operation.Name} via gRPC\");");
        sb.AppendLine();
        sb.AppendLine($"            var request = new {operation.Name}Request");
        sb.AppendLine("            {");
        sb.AppendLine("                // TODO: Map parameters to proto request");
        foreach (var param in operation.Parameters)
        {
            sb.AppendLine($"                // {ToPascalCase(param.Name)} = {param.Name},");
        }
        sb.AppendLine("            };");
        sb.AppendLine();
        sb.AppendLine($"            var response = await _grpcClient.{operation.Name}Async(request, cancellationToken: cancellationToken);");
        sb.AppendLine();
        sb.AppendLine("            // TODO: Map proto response to return type");
        sb.AppendLine($"            return default({returnType})!;");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (RpcException ex)");
        sb.AppendLine("        {");
        sb.AppendLine($"            _logger.LogError(ex, \"gRPC call to {operation.Name} failed\");");
        sb.AppendLine("            throw MapGrpcException(ex);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private string GenerateHttpClient(
        string interfaceName,
        string serviceName,
        string namespaceName,
        IReadOnlyList<WcfOperation> operations)
    {
        var sb = new StringBuilder();
        var className = $"{serviceName}HttpClient";

        // File header
        sb.AppendLine("using System.Net.Http.Json;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine();

        // Namespace
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();

        // Class documentation
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// HTTP client implementation for {serviceName}.");
        sb.AppendLine("/// Generated by NetLift from WCF service contract.");
        sb.AppendLine("/// </summary>");

        // Class declaration
        sb.AppendLine($"public sealed class {className} : {interfaceName}");
        sb.AppendLine("{");

        // Fields
        sb.AppendLine("    private readonly HttpClient _httpClient;");
        sb.AppendLine($"    private readonly ILogger<{className}> _logger;");
        sb.AppendLine();

        // Constructor
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Initializes a new instance of the <see cref=\"{className}\"/> class.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    /// <param name=\"httpClient\">The HTTP client.</param>");
        sb.AppendLine($"    /// <param name=\"logger\">The logger instance.</param>");
        sb.AppendLine($"    public {className}(HttpClient httpClient, ILogger<{className}> logger)");
        sb.AppendLine("    {");
        sb.AppendLine("        _httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));");
        sb.AppendLine("        _logger = logger ?? throw new ArgumentNullException(nameof(logger));");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Generate methods
        foreach (var operation in operations)
        {
            GenerateHttpMethod(sb, operation, serviceName);
        }

        // Close class
        sb.AppendLine("}");

        return sb.ToString();
    }

    private void GenerateHttpMethod(StringBuilder sb, WcfOperation operation, string serviceName)
    {
        var returnType = MapReturnType(operation.ReturnType);
        var parameters = string.Join(", ", operation.Parameters.Select(p => $"{p.Type} {p.Name}"));
        if (!string.IsNullOrEmpty(parameters))
            parameters += ", ";

        // Determine HTTP method (GET for queries, POST for commands)
        var httpMethod = DetermineHttpMethod(operation);
        var routeName = ToKebabCase(serviceName);

        // Method documentation
        sb.AppendLine("    /// <inheritdoc />");

        // Method signature
        sb.AppendLine($"    public async Task<{returnType}> {operation.Name}Async({parameters}CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");

        // Method body
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine($"            _logger.LogDebug(\"Calling {operation.Name} via HTTP\");");
        sb.AppendLine();

        if (httpMethod == "GET")
        {
            // Build query string
            sb.AppendLine($"            var url = $\"api/{routeName}/{ToKebabCase(operation.Name)}\";");
            if (operation.Parameters.Any())
            {
                sb.AppendLine("            // TODO: Add query parameters if needed");
            }
            sb.AppendLine();
            sb.AppendLine("            var response = await _httpClient.GetAsync(url, cancellationToken);");
        }
        else
        {
            // POST with request body
            sb.AppendLine("            var request = new");
            sb.AppendLine("            {");
            foreach (var param in operation.Parameters)
            {
                sb.AppendLine($"                {ToPascalCase(param.Name)} = {param.Name},");
            }
            sb.AppendLine("            };");
            sb.AppendLine();
            sb.AppendLine($"            var response = await _httpClient.PostAsJsonAsync($\"api/{routeName}/{ToKebabCase(operation.Name)}\", request, cancellationToken);");
        }

        sb.AppendLine();
        sb.AppendLine("            response.EnsureSuccessStatusCode();");
        sb.AppendLine();
        sb.AppendLine($"            var result = await response.Content.ReadFromJsonAsync<{returnType}>(cancellationToken: cancellationToken);");
        sb.AppendLine("            return result!;");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (HttpRequestException ex)");
        sb.AppendLine("        {");
        sb.AppendLine($"            _logger.LogError(ex, \"HTTP call to {operation.Name} failed\");");
        sb.AppendLine("            throw;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private string GenerateExtensions(string interfaceName, string serviceName, string namespaceName)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("using Grpc.Net.Client;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Polly;");
        sb.AppendLine("using Polly.Extensions.Http;");
        sb.AppendLine();

        // Namespace
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();

        // Class documentation
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Extension methods for {serviceName} client registration.");
        sb.AppendLine("/// Generated by NetLift from WCF service contract.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {serviceName}ClientExtensions");
        sb.AppendLine("{");

        // gRPC client registration
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Registers the gRPC client for {serviceName}.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"services\">The service collection.</param>");
        sb.AppendLine("    /// <param name=\"grpcAddress\">The gRPC service address.</param>");
        sb.AppendLine("    /// <returns>The service collection for chaining.</returns>");
        sb.AppendLine($"    public static IServiceCollection Add{serviceName}GrpcClient(");
        sb.AppendLine("        this IServiceCollection services,");
        sb.AppendLine("        string grpcAddress = \"https://localhost:5001\")");
        sb.AppendLine("    {");
        sb.AppendLine($"        services.AddGrpcClient<{serviceName}.{serviceName}Client>(options =>");
        sb.AppendLine("        {");
        sb.AppendLine("            options.Address = new Uri(grpcAddress);");
        sb.AppendLine("        })");
        sb.AppendLine("        .AddPolicyHandler(GetRetryPolicy());");
        sb.AppendLine();
        sb.AppendLine($"        services.AddSingleton<{interfaceName}, {serviceName}GrpcClient>();");
        sb.AppendLine();
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // HTTP client registration
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Registers the HTTP client for {serviceName}.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"services\">The service collection.</param>");
        sb.AppendLine("    /// <param name=\"httpBaseAddress\">The HTTP API base address.</param>");
        sb.AppendLine("    /// <returns>The service collection for chaining.</returns>");
        sb.AppendLine($"    public static IServiceCollection Add{serviceName}HttpClient(");
        sb.AppendLine("        this IServiceCollection services,");
        sb.AppendLine("        string httpBaseAddress = \"https://localhost:5000\")");
        sb.AppendLine("    {");
        sb.AppendLine($"        services.AddHttpClient<{interfaceName}, {serviceName}HttpClient>(client =>");
        sb.AppendLine("        {");
        sb.AppendLine("            client.BaseAddress = new Uri(httpBaseAddress);");
        sb.AppendLine("            client.Timeout = TimeSpan.FromSeconds(30);");
        sb.AppendLine("        })");
        sb.AppendLine("        .AddPolicyHandler(GetRetryPolicy())");
        sb.AppendLine("        .AddPolicyHandler(GetCircuitBreakerPolicy());");
        sb.AppendLine();
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Retry policy
        sb.AppendLine("    private static IAsyncPolicy<HttpResponseMessage> GetRetryPolicy()");
        sb.AppendLine("    {");
        sb.AppendLine("        return HttpPolicyExtensions");
        sb.AppendLine("            .HandleTransientHttpError()");
        sb.AppendLine("            .WaitAndRetryAsync(");
        sb.AppendLine("                retryCount: 3,");
        sb.AppendLine("                sleepDurationProvider: retryAttempt => TimeSpan.FromSeconds(Math.Pow(2, retryAttempt)),");
        sb.AppendLine("                onRetry: (outcome, timespan, retryCount, context) =>");
        sb.AppendLine("                {");
        sb.AppendLine("                    // TODO: Add logging for retry attempts");
        sb.AppendLine("                });");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Circuit breaker policy
        sb.AppendLine("    private static IAsyncPolicy<HttpResponseMessage> GetCircuitBreakerPolicy()");
        sb.AppendLine("    {");
        sb.AppendLine("        return HttpPolicyExtensions");
        sb.AppendLine("            .HandleTransientHttpError()");
        sb.AppendLine("            .CircuitBreakerAsync(");
        sb.AppendLine("                handledEventsAllowedBeforeBreaking: 5,");
        sb.AppendLine("                durationOfBreak: TimeSpan.FromSeconds(30),");
        sb.AppendLine("                onBreak: (outcome, timespan) =>");
        sb.AppendLine("                {");
        sb.AppendLine("                    // TODO: Add logging for circuit breaker open");
        sb.AppendLine("                },");
        sb.AppendLine("                onReset: () =>");
        sb.AppendLine("                {");
        sb.AppendLine("                    // TODO: Add logging for circuit breaker reset");
        sb.AppendLine("                });");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Exception mapper for gRPC
        sb.AppendLine("    private static Exception MapGrpcException(RpcException ex)");
        sb.AppendLine("    {");
        sb.AppendLine("        return ex.StatusCode switch");
        sb.AppendLine("        {");
        sb.AppendLine("            StatusCode.NotFound => new InvalidOperationException(\"Resource not found\", ex),");
        sb.AppendLine("            StatusCode.InvalidArgument => new ArgumentException(\"Invalid argument\", ex),");
        sb.AppendLine("            StatusCode.PermissionDenied => new UnauthorizedAccessException(\"Permission denied\", ex),");
        sb.AppendLine("            StatusCode.Unauthenticated => new UnauthorizedAccessException(\"Unauthenticated\", ex),");
        sb.AppendLine("            StatusCode.Unavailable => new InvalidOperationException(\"Service unavailable\", ex),");
        sb.AppendLine("            StatusCode.DeadlineExceeded => new TimeoutException(\"Request timeout\", ex),");
        sb.AppendLine("            _ => new InvalidOperationException($\"gRPC call failed: {ex.Status}\", ex)");
        sb.AppendLine("        };");
        sb.AppendLine("    }");

        // Close class
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string MapReturnType(string wcfReturnType)
    {
        // Remove Task<> wrapper if present (we'll add it back as async)
        if (wcfReturnType.StartsWith("Task<") && wcfReturnType.EndsWith(">"))
        {
            return wcfReturnType.Substring(5, wcfReturnType.Length - 6);
        }

        // Map void to empty response
        if (wcfReturnType == "void" || wcfReturnType == "Task")
        {
            return "bool"; // Return success flag for void operations
        }

        return wcfReturnType;
    }

    private static string DetermineHttpMethod(WcfOperation operation)
    {
        // Simple heuristic: operations starting with Get/Find/Search/Query are GET, others are POST
        var name = operation.Name.ToLowerInvariant();
        if (name.StartsWith("get") || name.StartsWith("find") ||
            name.StartsWith("search") || name.StartsWith("query") ||
            name.StartsWith("list"))
        {
            return "GET";
        }

        return "POST";
    }

    private static string ToPascalCase(string value)
    {
        if (string.IsNullOrEmpty(value))
            return value;

        return char.ToUpperInvariant(value[0]) + value.Substring(1);
    }

    private static string ToKebabCase(string value)
    {
        if (string.IsNullOrEmpty(value))
            return value;

        var sb = new StringBuilder();
        for (int i = 0; i < value.Length; i++)
        {
            if (i > 0 && char.IsUpper(value[i]))
            {
                sb.Append('-');
            }
            sb.Append(char.ToLowerInvariant(value[i]));
        }
        return sb.ToString();
    }
}
