using System.Text;
using NetLift.Core.Interfaces;
using NetLift.Core.Models.Wcf;

namespace NetLift.Transforms.Wcf.Generators;

/// <summary>
/// Generates gRPC service implementation classes from WCF service contracts.
/// </summary>
public sealed class GrpcServiceGenerator : IGrpcServiceGenerator
{
    private readonly List<string> _diagnostics = [];
    private int _confidenceScore = 100;

    /// <inheritdoc />
    public int ConfidenceScore => _confidenceScore;

    /// <inheritdoc />
    public IReadOnlyCollection<string> Diagnostics => _diagnostics.AsReadOnly();

    /// <inheritdoc />
    public GrpcServiceInfo Generate(WcfServiceContract serviceContract, string targetNamespace)
    {
        if (serviceContract == null)
            throw new ArgumentNullException(nameof(serviceContract));
        if (string.IsNullOrWhiteSpace(targetNamespace))
            throw new ArgumentException("Target namespace cannot be null or whitespace.", nameof(targetNamespace));

        // Reset state
        _diagnostics.Clear();
        _confidenceScore = 100;

        // Derive service and class names
        var serviceName = serviceContract.Name ??
            (serviceContract.InterfaceName.StartsWith('I') && serviceContract.InterfaceName.Length > 1
                ? serviceContract.InterfaceName.Substring(1)
                : serviceContract.InterfaceName);
        var className = $"{serviceName}Grpc";
        var baseClassName = $"{serviceName}.{serviceName}Base";
        var businessServiceInterface = $"I{serviceName}BusinessService";

        // Check for unsupported features
        if (serviceContract.SessionRequired)
        {
            _diagnostics.Add($"Service contract requires sessions. gRPC does not support stateful sessions. Consider using correlation IDs.");
            _confidenceScore = Math.Min(_confidenceScore, 70);
        }

        if (!string.IsNullOrWhiteSpace(serviceContract.CallbackContract))
        {
            _diagnostics.Add($"Service contract uses duplex pattern with callback contract '{serviceContract.CallbackContract}'. gRPC supports bidirectional streaming instead.");
            _confidenceScore = Math.Min(_confidenceScore, 65);
        }

        // Generate service code
        var serviceCode = GenerateServiceClass(
            className,
            targetNamespace,
            baseClassName,
            businessServiceInterface,
            serviceContract.Operations
        );

        // Generate extensions code
        var extensionsCode = GenerateExtensionMethods(
            className,
            targetNamespace,
            serviceName
        );

        // Build method info list
        var methods = serviceContract.Operations.Select(op => new GrpcMethodInfo
        {
            Name = op.Name,
            RequestType = $"{op.Name}Request",
            ResponseType = $"{op.Name}Response",
            Documentation = op.XmlDocumentation
        }).ToList();

        return new GrpcServiceInfo
        {
            ClassName = className,
            Namespace = targetNamespace,
            BaseClassName = baseClassName,
            ServiceCode = serviceCode,
            ExtensionsCode = extensionsCode,
            Methods = methods
        };
    }

    private string GenerateServiceClass(
        string className,
        string namespaceName,
        string baseClassName,
        string businessServiceInterface,
        IReadOnlyList<WcfOperation> operations)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("using Grpc.Core;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine();

        // Namespace
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();

        // Class documentation
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// gRPC service implementation for {className.Replace("Grpc", "")}.");
        sb.AppendLine("/// Generated by NetLift from WCF service contract.");
        sb.AppendLine("/// </summary>");

        // Class declaration
        sb.AppendLine($"public class {className} : {baseClassName}");
        sb.AppendLine("{");

        // Fields
        sb.AppendLine($"    private readonly ILogger<{className}> _logger;");
        sb.AppendLine($"    private readonly {businessServiceInterface} _businessService;");
        sb.AppendLine();

        // Constructor
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Initializes a new instance of the <see cref=\"{className}\"/> class.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    /// <param name=\"logger\">The logger instance.</param>");
        sb.AppendLine($"    /// <param name=\"businessService\">The business service implementation.</param>");
        sb.AppendLine($"    public {className}(ILogger<{className}> logger, {businessServiceInterface} businessService)");
        sb.AppendLine("    {");
        sb.AppendLine("        _logger = logger ?? throw new ArgumentNullException(nameof(logger));");
        sb.AppendLine("        _businessService = businessService ?? throw new ArgumentNullException(nameof(businessService));");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Generate methods
        foreach (var operation in operations)
        {
            GenerateMethodOverride(sb, operation);
        }

        // Close class
        sb.AppendLine("}");

        return sb.ToString();
    }

    private void GenerateMethodOverride(StringBuilder sb, WcfOperation operation)
    {
        var requestType = $"{operation.Name}Request";
        var responseType = $"{operation.Name}Response";

        // Method documentation
        sb.AppendLine("    /// <summary>");
        if (!string.IsNullOrWhiteSpace(operation.XmlDocumentation))
        {
            foreach (var line in operation.XmlDocumentation.Split('\n'))
            {
                sb.AppendLine($"    /// {line.Trim()}");
            }
        }
        else
        {
            sb.AppendLine($"    /// Handles {operation.Name} RPC call.");
        }
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    /// <param name=\"request\">The request message.</param>");
        sb.AppendLine($"    /// <param name=\"context\">The server call context.</param>");
        sb.AppendLine($"    /// <returns>The response message.</returns>");

        // Method signature
        sb.AppendLine($"    public override async Task<{responseType}> {operation.Name}({requestType} request, ServerCallContext context)");
        sb.AppendLine("    {");

        // Method body
        sb.AppendLine($"        _logger.LogDebug(\"{operation.Name} called with request: {{@Request}}\", request);");
        sb.AppendLine();

        if (operation.IsOneWay)
        {
            sb.AppendLine($"        // TODO: Original WCF operation was one-way. gRPC requires request-response pattern.");
            _diagnostics.Add($"Operation '{operation.Name}' was one-way in WCF. gRPC requires a response. Review implementation.");
            _confidenceScore = Math.Min(_confidenceScore, 80);
        }

        sb.AppendLine("        // TODO: Implement business logic by calling _businessService methods");
        sb.AppendLine("        // Example:");
        sb.AppendLine($"        // var result = await _businessService.{operation.Name}Async(...);");
        sb.AppendLine($"        // return new {responseType} {{ ... }};");
        sb.AppendLine();
        sb.AppendLine("        throw new RpcException(new Status(StatusCode.Unimplemented, \"Method not implemented yet\"));");

        // Close method
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private string GenerateExtensionMethods(
        string className,
        string namespaceName,
        string serviceName)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();

        // Namespace
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();

        // Extensions class
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Extension methods for {className} service registration and endpoint mapping.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {className}Extensions");
        sb.AppendLine("{");

        // AddServices method
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Registers {className} and its dependencies in the DI container.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"services\">The service collection.</param>");
        sb.AppendLine("    /// <returns>The service collection for chaining.</returns>");
        sb.AppendLine($"    public static IServiceCollection Add{serviceName}(this IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine("        // TODO: Register business service implementation");
        sb.AppendLine($"        // services.AddScoped<I{serviceName}BusinessService, {serviceName}BusinessService>();");
        sb.AppendLine();
        sb.AppendLine($"        services.AddGrpc();");
        sb.AppendLine();
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // MapEndpoint method
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Maps the {className} gRPC endpoint.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"builder\">The endpoint route builder.</param>");
        sb.AppendLine("    /// <returns>The gRPC service endpoint convention builder.</returns>");
        sb.AppendLine($"    public static GrpcServiceEndpointConventionBuilder Map{serviceName}(this IEndpointRouteBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return builder.MapGrpcService<{className}>();");
        sb.AppendLine("    }");

        // Close class
        sb.AppendLine("}");

        return sb.ToString();
    }
}
