using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using NetLift.Core.Interfaces;
using NetLift.Core.Models.Wcf;

namespace NetLift.Transforms.Wcf.Generators;

/// <summary>
/// Generates Protocol Buffer (.proto) files from WCF service and data contracts.
/// </summary>
public sealed class ProtoGenerator : IProtoGenerator
{
    private readonly List<string> _diagnostics = [];
    private readonly HashSet<string> _imports = [];
    private int _confidenceScore = 100;

    /// <inheritdoc />
    public int ConfidenceScore => _confidenceScore;

    /// <inheritdoc />
    public IReadOnlyCollection<string> Diagnostics => _diagnostics.AsReadOnly();

    /// <inheritdoc />
    public ProtoFileInfo Generate(WcfServiceContract serviceContract, IReadOnlyList<WcfDataContract> dataContracts)
    {
        if (serviceContract == null)
            throw new ArgumentNullException(nameof(serviceContract));
        if (dataContracts == null)
            throw new ArgumentNullException(nameof(dataContracts));

        // Reset state
        _diagnostics.Clear();
        _imports.Clear();
        _confidenceScore = 100;

        var sb = new StringBuilder();

        // Extract package name and C# namespace
        var packageName = DerivePackageName(serviceContract);
        var csharpNamespace = DeriveCSharpNamespace(serviceContract);

        // Generate file header comment
        var serviceName = serviceContract.Name ?? serviceContract.InterfaceName;
        sb.AppendLine($"// {ToSnakeCase(serviceName)}.proto");
        sb.AppendLine($"// Generated by NetLift from {serviceContract.InterfaceName}");
        sb.AppendLine();

        // Syntax declaration
        sb.AppendLine("syntax = \"proto3\";");
        sb.AppendLine();

        // Package declaration
        sb.AppendLine($"package {packageName};");
        sb.AppendLine();

        // Generate imports (will be populated during type mapping)
        var tempImports = new HashSet<string>();

        // Generate service definition
        sb.AppendLine($"service {serviceName.TrimStart('I')} {{");

        foreach (var operation in serviceContract.Operations)
        {
            if (operation.IsOneWay)
            {
                _diagnostics.Add($"Operation '{operation.Name}' is one-way. gRPC requires request-response pattern. Generating empty response message.");
                _confidenceScore = Math.Min(_confidenceScore, 85);
            }

            // Add XML documentation as comment
            if (!string.IsNullOrWhiteSpace(operation.XmlDocumentation))
            {
                foreach (var line in operation.XmlDocumentation.Split('\n'))
                {
                    sb.AppendLine($"  // {line.Trim()}");
                }
            }

            var requestName = $"{operation.Name}Request";
            var responseName = $"{operation.Name}Response";
            sb.AppendLine($"  rpc {operation.Name} ({requestName}) returns ({responseName});");
        }

        sb.AppendLine("}");
        sb.AppendLine();

        // Generate request/response messages for each operation
        foreach (var operation in serviceContract.Operations)
        {
            // Request message
            sb.AppendLine($"message {operation.Name}Request {{");
            for (int i = 0; i < operation.Parameters.Count; i++)
            {
                var param = operation.Parameters[i];
                var protoType = MapToProtoType(param, tempImports);
                var fieldName = ToSnakeCase(param.Name);
                sb.AppendLine($"  {protoType} {fieldName} = {i + 1};");
            }
            sb.AppendLine("}");
            sb.AppendLine();

            // Response message
            sb.AppendLine($"message {operation.Name}Response {{");
            if (operation.ReturnType != "void" && operation.ReturnType != "Task")
            {
                var returnType = operation.ReturnType;
                // Strip Task<T> wrapper
                if (returnType.StartsWith("Task<") && returnType.EndsWith(">"))
                {
                    returnType = returnType.Substring(5, returnType.Length - 6);
                }

                var protoReturnType = MapTypeNameToProto(returnType, false, false, tempImports);
                var fieldName = ToSnakeCase(returnType.Split('.').Last().Replace("[]", ""));
                sb.AppendLine($"  {protoReturnType} {fieldName} = 1;");
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // Generate data contract messages
        foreach (var dataContract in dataContracts)
        {
            if (dataContract.IsEnum)
            {
                GenerateEnumMessage(sb, dataContract);
            }
            else
            {
                GenerateDataContractMessage(sb, dataContract, tempImports);
            }
        }

        // Build final content with imports at the top
        var finalContent = new StringBuilder();
        finalContent.AppendLine($"// {ToSnakeCase(serviceName)}.proto");
        finalContent.AppendLine($"// Generated by NetLift from {serviceContract.InterfaceName}");
        finalContent.AppendLine();
        finalContent.AppendLine("syntax = \"proto3\";");
        finalContent.AppendLine();
        finalContent.AppendLine($"package {packageName};");
        finalContent.AppendLine();

        // Add imports
        var sortedImports = tempImports.OrderBy(x => x).ToList();
        if (sortedImports.Any())
        {
            foreach (var import in sortedImports)
            {
                finalContent.AppendLine($"import \"{import}\";");
            }
            finalContent.AppendLine();
        }

        // Add C# namespace option
        finalContent.AppendLine($"option csharp_namespace = \"{csharpNamespace}\";");
        finalContent.AppendLine();

        // Add the rest of the content (skip the header we already wrote)
        var lines = sb.ToString().Split('\n').Skip(5).ToArray();
        finalContent.AppendLine(string.Join('\n', lines));

        var fileName = $"{ToSnakeCase(serviceName.TrimStart('I'))}.proto";

        return new ProtoFileInfo
        {
            FileName = fileName,
            Content = finalContent.ToString(),
            PackageName = packageName,
            CSharpNamespace = csharpNamespace,
            Imports = sortedImports
        };
    }

    private void GenerateEnumMessage(StringBuilder sb, WcfDataContract dataContract)
    {
        var enumName = dataContract.Name ?? dataContract.TypeName;
        sb.AppendLine($"enum {enumName} {{");

        // Proto3 enums must have a zero value
        bool hasZero = dataContract.EnumMembers.Any(m => m.Value == 0);
        if (!hasZero)
        {
            sb.AppendLine($"  {enumName.ToUpperInvariant()}_UNSPECIFIED = 0;");
            _diagnostics.Add($"Enum '{enumName}' does not have a zero value. Added UNSPECIFIED = 0 as required by proto3.");
            _confidenceScore = Math.Min(_confidenceScore, 90);
        }

        foreach (var member in dataContract.EnumMembers)
        {
            var memberName = member.SerializedName ?? member.Name;
            var constantName = ToConstantCase(memberName);
            sb.AppendLine($"  {constantName} = {member.Value};");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private void GenerateDataContractMessage(StringBuilder sb, WcfDataContract dataContract, HashSet<string> imports)
    {
        var messageName = dataContract.Name ?? dataContract.TypeName;
        sb.AppendLine($"message {messageName} {{");

        // Sort properties by Order if specified, otherwise preserve declaration order
        // Group by Order, but maintain original order within each group
        var sortedProperties = dataContract.Properties
            .Select((prop, index) => new { Property = prop, OriginalIndex = index })
            .OrderBy(x => x.Property.Order)
            .ThenBy(x => x.OriginalIndex)
            .Select(x => x.Property)
            .ToList();

        for (int i = 0; i < sortedProperties.Count; i++)
        {
            var property = sortedProperties[i];
            var protoType = MapPropertyToProtoType(property, imports);
            var fieldName = ToSnakeCase(property.Name);
            sb.AppendLine($"  {protoType} {fieldName} = {i + 1};");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private string MapToProtoType(WcfParameter parameter, HashSet<string> imports)
    {
        return MapTypeNameToProto(parameter.Type, parameter.IsArray, parameter.IsNullable, imports);
    }

    private string MapPropertyToProtoType(WcfDataMember property, HashSet<string> imports)
    {
        return MapTypeNameToProto(property.Type, property.IsCollection, property.IsNullable, imports);
    }

    private string MapTypeNameToProto(string typeName, bool isArray, bool isNullable, HashSet<string> imports)
    {
        // Handle generic types (e.g., List<T>, Dictionary<K,V>) using Roslyn
        if (typeName.Contains('<'))
        {
            var (isCollection, elementType) = ParseGenericType(typeName);
            if (isCollection)
            {
                var elementProtoType = MapTypeNameToProto(elementType, false, false, imports);
                return $"repeated {elementProtoType}";
            }
        }

        // Handle arrays (e.g., int[], string[])
        if (isArray || typeName.EndsWith("[]"))
        {
            var elementType = typeName.TrimEnd('[', ']');
            var elementProtoType = MapTypeNameToProto(elementType, false, false, imports);
            return $"repeated {elementProtoType}";
        }

        // Clean up type name
        typeName = typeName.Split('.').Last().Replace("?", "");

        // Map primitive types
        var protoType = typeName switch
        {
            "Int32" or "int" => "int32",
            "Int64" or "long" => "int64",
            "UInt32" or "uint" => "uint32",
            "UInt64" or "ulong" => "uint64",
            "Boolean" or "bool" => "bool",
            "String" or "string" => "string",
            "Double" or "double" => "double",
            "Single" or "float" => "float",
            "Byte" or "byte" => "uint32",
            "SByte" or "sbyte" => "int32",
            "Int16" or "short" => "int32",
            "UInt16" or "ushort" => "uint32",
            "Char" or "char" => "string",
            "Decimal" or "decimal" => HandleDecimal(imports),
            "DateTime" => HandleDateTime(imports),
            "DateTimeOffset" => HandleDateTime(imports),
            "TimeSpan" => HandleDuration(imports),
            "Guid" => "string",
            "ByteArray" or "Byte[]" or "byte[]" => "bytes",
            _ => typeName // Custom type - assume it's a message
        };

        // Handle nullable value types with wrappers
        if (isNullable && IsValueType(typeName))
        {
            protoType = protoType switch
            {
                "int32" => HandleInt32Value(imports),
                "int64" => HandleInt64Value(imports),
                "uint32" => HandleUInt32Value(imports),
                "uint64" => HandleUInt64Value(imports),
                "bool" => HandleBoolValue(imports),
                "double" => HandleDoubleValue(imports),
                "float" => HandleFloatValue(imports),
                "string" => HandleStringValue(imports),
                "bytes" => HandleBytesValue(imports),
                _ => protoType
            };
        }

        return protoType;
    }

    private bool IsValueType(string typeName)
    {
        return typeName switch
        {
            "Int32" or "int" or "Int64" or "long" or "UInt32" or "uint" or "UInt64" or "ulong" or
            "Boolean" or "bool" or "Double" or "double" or "Single" or "float" or
            "Byte" or "byte" or "SByte" or "sbyte" or "Int16" or "short" or "UInt16" or "ushort" or
            "Char" or "char" or "Decimal" or "decimal" or "DateTime" or "DateTimeOffset" or
            "TimeSpan" or "Guid" => true,
            _ => false
        };
    }

    private string HandleDecimal(HashSet<string> imports)
    {
        _diagnostics.Add("Decimal type mapped to double. Precision may be lost. Consider using a custom Decimal message type.");
        _confidenceScore = Math.Min(_confidenceScore, 80);
        return "double";
    }

    private string HandleDateTime(HashSet<string> imports)
    {
        imports.Add("google/protobuf/timestamp.proto");
        return "google.protobuf.Timestamp";
    }

    private string HandleDuration(HashSet<string> imports)
    {
        imports.Add("google/protobuf/duration.proto");
        return "google.protobuf.Duration";
    }

    private string HandleInt32Value(HashSet<string> imports)
    {
        imports.Add("google/protobuf/wrappers.proto");
        return "google.protobuf.Int32Value";
    }

    private string HandleInt64Value(HashSet<string> imports)
    {
        imports.Add("google/protobuf/wrappers.proto");
        return "google.protobuf.Int64Value";
    }

    private string HandleUInt32Value(HashSet<string> imports)
    {
        imports.Add("google/protobuf/wrappers.proto");
        return "google.protobuf.UInt32Value";
    }

    private string HandleUInt64Value(HashSet<string> imports)
    {
        imports.Add("google/protobuf/wrappers.proto");
        return "google.protobuf.UInt64Value";
    }

    private string HandleBoolValue(HashSet<string> imports)
    {
        imports.Add("google/protobuf/wrappers.proto");
        return "google.protobuf.BoolValue";
    }

    private string HandleDoubleValue(HashSet<string> imports)
    {
        imports.Add("google/protobuf/wrappers.proto");
        return "google.protobuf.DoubleValue";
    }

    private string HandleFloatValue(HashSet<string> imports)
    {
        imports.Add("google/protobuf/wrappers.proto");
        return "google.protobuf.FloatValue";
    }

    private string HandleStringValue(HashSet<string> imports)
    {
        imports.Add("google/protobuf/wrappers.proto");
        return "google.protobuf.StringValue";
    }

    private string HandleBytesValue(HashSet<string> imports)
    {
        imports.Add("google/protobuf/wrappers.proto");
        return "google.protobuf.BytesValue";
    }

    private string DerivePackageName(WcfServiceContract serviceContract)
    {
        // Try to use the ServiceContract namespace attribute
        if (!string.IsNullOrWhiteSpace(serviceContract.Namespace) &&
            serviceContract.Namespace.StartsWith("http"))
        {
            // Extract from URL: http://company.com/services -> company.services
            var uri = new Uri(serviceContract.Namespace);
            var parts = uri.Host.Split('.').Reverse()
                .Concat(uri.AbsolutePath.Split('/', StringSplitOptions.RemoveEmptyEntries))
                .Select(p => p.ToLowerInvariant());
            return string.Join('.', parts);
        }

        // Fall back to C# namespace
        var namespaceParts = serviceContract.FullyQualifiedName
            .Split('.')
            .SkipLast(1) // Remove interface name
            .Select(p => p.ToLowerInvariant());

        return string.Join('.', namespaceParts);
    }

    private string DeriveCSharpNamespace(WcfServiceContract serviceContract)
    {
        // Extract namespace from FullyQualifiedName
        var parts = serviceContract.FullyQualifiedName.Split('.');
        if (parts.Length > 1)
        {
            var ns = string.Join('.', parts.SkipLast(1));
            return $"{ns}.Grpc";
        }

        return "Generated.Grpc";
    }

    private string ToSnakeCase(string input)
    {
        if (string.IsNullOrWhiteSpace(input))
            return input;

        // Insert underscore before uppercase letters (except at start)
        var result = Regex.Replace(input, "(?<!^)([A-Z])", "_$1");
        return result.ToLowerInvariant();
    }

    private string ToConstantCase(string input)
    {
        if (string.IsNullOrWhiteSpace(input))
            return input;

        // Convert to snake_case first, then uppercase
        return ToSnakeCase(input).ToUpperInvariant();
    }

    /// <summary>
    /// Parses a type name using Roslyn to detect generic collections.
    /// Handles nested generics and multiple type arguments correctly.
    /// </summary>
    /// <param name="typeName">The type name to parse (e.g., "List&lt;string&gt;", "Dictionary&lt;int, List&lt;string&gt;&gt;")</param>
    /// <returns>A tuple indicating if it's a collection and the element type if applicable</returns>
    private static (bool IsCollection, string ElementType) ParseGenericType(string typeName)
    {
        try
        {
            var type = SyntaxFactory.ParseTypeName(typeName);

            if (type is GenericNameSyntax genericName)
            {
                var name = genericName.Identifier.Text;
                var isCollection = name is "List" or "IList" or "IEnumerable" or "ICollection"
                                  or "IReadOnlyList" or "IReadOnlyCollection";

                if (isCollection && genericName.TypeArgumentList.Arguments.Count == 1)
                {
                    var elementType = genericName.TypeArgumentList.Arguments[0].ToString();
                    return (true, elementType);
                }

                // Handle qualified names like System.Collections.Generic.List<T>
                if (!isCollection && type is QualifiedNameSyntax qualifiedName &&
                    qualifiedName.Right is GenericNameSyntax rightGeneric)
                {
                    var rightName = rightGeneric.Identifier.Text;
                    var rightIsCollection = rightName is "List" or "IList" or "IEnumerable" or "ICollection"
                                           or "IReadOnlyList" or "IReadOnlyCollection";

                    if (rightIsCollection && rightGeneric.TypeArgumentList.Arguments.Count == 1)
                    {
                        var elementType = rightGeneric.TypeArgumentList.Arguments[0].ToString();
                        return (true, elementType);
                    }
                }
            }

            return (false, typeName);
        }
        catch
        {
            // If parsing fails, fall back to non-collection
            return (false, typeName);
        }
    }
}
